version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: assetflow-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: assetflow
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
