import { useEffect, useMemo, useState } from "react";
import { apiClient } from "../lib/api-client";

const FILTERS = ["All", "Alerts", "Approvals", "Bookings"];

function bucket(notification) {
  const type = String(notification.type || "").toUpperCase();

  if (type.includes("BOOKING")) return "Bookings";
  if (type.includes("TRANSFER") || type.includes("APPROVAL") || type.includes("PROMOT")) return "Approvals";
  if (type.includes("MAINTENANCE") || type.includes("ALERT") || type.includes("OVERDUE")) return "Alerts";
  return "All";
}

export default function Notifications() {
  const [notifications, setNotifications] = useState([]);
  const [filter, setFilter] = useState("All");
  const [message, setMessage] = useState("");

  useEffect(() => {
    loadNotifications();
  }, []);

  async function loadNotifications() {
    setMessage("");
    try {
      const data = await apiClient.get("/notifications");
      setNotifications(data);
    } catch (error) {
      setMessage(error.message || "Failed to load notifications.");
    }
  }

  async function markRead(id) {
    try {
      await apiClient.put(`/notifications/${id}/read`);
      setNotifications((current) => current.map((item) => (item.id === id ? { ...item, isRead: true } : item)));
    } catch (error) {
      setMessage(error.message || "Failed to update notification.");
    }
  }

  const enriched = useMemo(
    () => notifications.map((notification) => ({ ...notification, bucket: bucket(notification) })),
    [notifications],
  );

  const filtered = enriched.filter((notification) => filter === "All" || notification.bucket === filter);

  return (
    <div className="p-8 min-h-screen">
      <div className="mb-6 flex items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Notifications</h1>
          <p className="mt-1 text-sm text-slate-500">Live notification feed generated by backend actions.</p>
        </div>
        <button onClick={loadNotifications} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700">
          Refresh
        </button>
      </div>

      <div className="mb-4 flex flex-wrap gap-2">
        {FILTERS.map((item) => (
          <button
            key={item}
            onClick={() => setFilter(item)}
            className={`rounded-xl px-4 py-2 text-sm font-medium ${
              filter === item ? "bg-slate-900 text-white" : "bg-white border border-slate-200 text-slate-700"
            }`}
          >
            {item}
          </button>
        ))}
      </div>

      {message && (
        <div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {message}
        </div>
      )}

      <div className="rounded-2xl border border-slate-100 bg-white shadow-sm">
        {filtered.length === 0 ? (
          <div className="p-8 text-sm text-slate-500">Nothing here yet.</div>
        ) : (
          <div className="divide-y divide-slate-100">
            {filtered.map((item) => (
              <div key={item.id} className={`flex items-start justify-between gap-4 p-4 ${item.isRead ? "" : "bg-slate-50/60"}`}>
                <div>
                  <p className="text-sm font-medium text-slate-900">{item.message}</p>
                  <p className="mt-1 text-xs text-slate-500">
                    {item.type} · {new Date(item.createdAt).toLocaleString()}
                  </p>
                </div>
                {!item.isRead && (
                  <button
                    onClick={() => markRead(item.id)}
                    className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-700"
                  >
                    Mark read
                  </button>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
